security:
  jwt:
    secret: 'LanMaoXa7'
    expire: 72
  exposed-endpoints:
    - method: GET
      path: /favicon.ico
    - method: POST
      path: /webhook/**
    - method: GET
      path: /auth/**
    - method: ANY  # 表示允许所有方法（GET、POST、PUT 等）
      path: /test/**

